# lmake_semver/Makefile.toml
# https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    dependencies = [
        "help_command_order"
    ]

    [tasks.dev]
    description = "cargo build development"
    clear = true
    dependencies = [
        "build_dev",
    ]

    [tasks.release]
    description = "cargo build release"
    clear = true
    dependencies = [
        "increment_patch",
        "build_release",
    ]

    [tasks.run_rel1]
    description = "run the app with parameters if needed"
    clear = true
    script = [
        "echo target/release/lmake_semver",
        "target/release/lmake_semver ",
    ]

    [tasks.run_rel2]
    description = "run the app with parameters if needed"
    clear = true
    script = [
        "echo target/release/lmake_semver --help",
        "target/release/lmake_semver --help",
    ]

    [tasks.run_rel3]
    description = "run the app with parameters if needed"
    clear = true
    script = [
        "echo target/release/lmake_semver --increment=minor",
        "target/release/lmake_semver --increment=patch",
    ]

    [tasks.run_rel4]
    description = "run the app with parameters if needed"
    clear = true
    script = [
        "echo target/release/lmake_semver --increment=minor",
        "target/release/lmake_semver --increment=minor",
    ]

    [tasks.run_rel5]
    description = "run the app with parameters if needed"
    clear = true
    script = [
        "echo target/release/lmake_semver --increment=blahblah",
        "target/release/lmake_semver --increment=blahblah",
    ]

    [tasks.doc]
    description = "create docs from comments"
    clear = true
    dependencies = [
		"include_readme",
        "cargo_doc",
		"doc_copy",
    ]
    
    [tasks.sshadd]
    description = "adds identity to ssh-agent for git and publish operations"
    clear = true
    script = [
        "ssh-add /home/luciano/.ssh/luciano_googlecloud",
        "ssh-add /home/luciano/.ssh/lucianobestia_mac",
        "ssh-add -l",
    ]

    [tasks.gitpush]
    description = "push the commits to github, uses ssh agent"
    clear = true
    script = [
        "git push",
    ]

	[tasks.crates_io_dry_run]
	clear = true
	description = "prepare before publishing to crates.io with dry-run"
	command = "cargo"
	args = ["publish","--dry-run"]

    [tasks.crates_io_publish]
	clear = true
	description = "publish to crates.io. TODO: maybe tag the git with the version?"
    # git tag -a v0.4.0 -m "version 0.4.0"
	command = "cargo"
	args = ["publish",]

    [tasks.increment_minor]
    description = "increments semver minor"
    clear = true
    script = [
        "lmake_semver --increment=minor",
    ]
# endregion

[tasks.help_command_order]
clear = true
private = true
description = "help developer to understand the order of exec commands"
script= [
"echo ",
"echo ORDER OF EXECUTING MAKE TASKS:",
"echo 01. ..... change your code in the editor",
"echo 02. cargo make dev - build developer versions",
"echo 03. cargo make run_dev1 - run the developer build. 1,2,3,4 are different arguments",
"echo 04. cargo make test - test the test code",
"echo 05. cargo make release - build release version, it changes the version number in cargo.toml",
"echo 06. cargo make run_rel1 - run the release build. 1,2,3,4 are different arguments",
"echo 07. cargo make doc - copies from cargo.toml to readme.md and from readme.md to main.rs or lib.rs, generates doc and copies to docs folder.",
"echo 08. ..... run a git commit",
"echo 09. cargo make sshadd - run only once - adds identity to ssh-agent for git and publish operations",
"echo 10. cargo make gitpush - git commit and git push",
"echo 11. cargo make crates_io_dry_run - prepare publishing for crates.io",
"echo 12. ..... run a git tag -a v0.4.0 -m 'version 0.4.0' ",
"echo 13. cargo make crates_io_publish - publish to crates.io",
"echo "]

[tasks.build_dev]
clear = true
private = true
description = "build wasm in dev mode"
command = "cargo"
args = ["build"]

[tasks.include_readme]
clear = true
private = true
description = "copy the content of readme.md into *.rs comments (for the docs)"
script= ["lmake_readme"]

[tasks.cargo_doc]
clear = true
private = true
description = "call cargo doc"
command="cargo"
args=["doc","--no-deps","--document-private-items"]

[tasks.doc_copy]
clear = true
private = true
description = "copy doc folder as docs (out of folder target), so it can be git comitted"
script = [
    "\\rsync -avz --delete-after target/doc/*  docs/"
]

[tasks.build_release]
description = "build for release"
clear = true
private = true
command = "cargo"
args = ["build","--release"]


[tasks.increment_patch]
clear = true
private = true
description = "increment semver patch"
script= ["lmake_semver --increment=patch"]
